version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: php-symfony
    environment:
      - SYMFONY_ENV=dev
      - DATABASE_URL=postgresql://symfony_user:symfony_pass@db:5432/symfony_db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_pass
      POSTGRES_DB: symfony_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && ng serve --host 0.0.0.0"

volumes:
  postgres-data:
